version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  backend:
    image: gashev1989/foodgram:latest
#    build: ../backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - docs:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media
    depends_on:
      - backend
volumes:
  static_value:
  media_value:
  data_value:
  docs:
